{% set name = "libdiscid" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/metabrainz/libdiscid/archive/v{{ version }}.tar.gz
  sha256: df7b19a125e31bb15bb0cebf338fb7a44cc20b76adf5de1798315a2056ff2d5a
  patches:
    - 0001-Update-disc_win32.c.patch    # [win]
    - Cmake.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libdiscid', max_pin='x.x') }}

requirements:
  build:
    - ninja  # [win]
    - make  # [not win]
    - cmake
    - {{ compiler('c') }}
    - m2-patch  # [win]
test:
  commands:
    - test -f "${PREFIX}/lib/libdiscid.so.0"  # [linux]
    - test -f "${PREFIX}/lib/libdiscid.dylib"  # [osx]
    - test -f "${PREFIX}/include/discid/discid.h"  # [unix]
    - if not exist %LIBRARY_LIB%\*discid.dll exit 1  # [win]
    - if not exist %LIBRARY_INC%\discid\discid.h exit 1  # [win]

about:
  home: https://musicbrainz.org/doc/libdiscid
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: A Library for creating MusicBrainz DiscIDs
  dev_url: https://github.com/metabrainz/libdiscid
  doc_url: https://musicbrainz.org/doc/libdiscid

extra:
  recipe-maintainers:
    - HeavyTony2
